version: "3.6"

services:
  db:
    image: postgres:12
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "storybook_demo"
      POSTGRES_USER: "storybook_demo"
    ports:
      - "${DB_PORT:-5432}:5432"

volumes:
  postgres-volume:

networks:
  default:
    driver: bridge
